name: project_library
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  flutter_bloc: ^8.0.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  file_picker: ^5.0.0
  cached_network_image: ^3.2.0
  syncfusion_flutter_pdfviewer: ^30.1.42  
  path_provider: ^2.0.14
  cupertino_icons: ^1.0.8
  flutterfire_cli: ^1.3.1
  url_launcher: ^6.3.2
  dio: ^5.3.2
  image_picker: ^0.8.7+4
  fluttertoast: ^8.2.12
  turnable_page: ^0.0.1+1
  pdf_render: ^1.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
