// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8LNgRz0KSmE03K6sCwC7dj8y9LYY5J0',
    appId: '1:301258585771:web:6e35b690ffccfc18d9a9ee',
    messagingSenderId: '301258585771',
    projectId: 'project-library-a74b3',
    authDomain: 'project-library-a74b3.firebaseapp.com',
    storageBucket: 'project-library-a74b3.firebasestorage.app',
    measurementId: 'G-S3VVPJYGF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaNbKTjrn7Sa85VqrtQM2JEI-IbE67Do0',
    appId: '1:301258585771:android:0dbb944a0e7a0939d9a9ee',
    messagingSenderId: '301258585771',
    projectId: 'project-library-a74b3',
    storageBucket: 'project-library-a74b3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT8LNgRz0KSmE03K6sCwC7dj8y9LYY5J0',
    appId: '1:301258585771:web:f987804807d6fbacd9a9ee',
    messagingSenderId: '301258585771',
    projectId: 'project-library-a74b3',
    authDomain: 'project-library-a74b3.firebaseapp.com',
    storageBucket: 'project-library-a74b3.firebasestorage.app',
    measurementId: 'G-PXBXLPWBFM',
  );
}
